name: Release (Linux)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: false
        default: 'manual'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxkbcommon-dev \
            libssl-dev \
            libgtk-3-dev \
            libwayland-dev \
            libxkbcommon-x11-dev \
            wget \
            jq

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package tarball
        run: |
          mkdir -p release
          cp target/release/awsdash release/
          cp README.md release/
          cp LICENSE-APACHE release/
          cd release
          tar -czvf ../awsdash-linux-x86_64.tar.gz *

      - name: Create AppImage
        run: |
          # Download appimagetool
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

          # Create AppDir structure
          mkdir -p AWSDash.AppDir/usr/bin
          mkdir -p AWSDash.AppDir/usr/share/applications
          mkdir -p AWSDash.AppDir/usr/share/icons/hicolor/256x256/apps

          # Copy binary
          cp target/release/awsdash AWSDash.AppDir/usr/bin/awsdash

          # Copy icon or create placeholder
          if [ -f dash-icon.png ]; then
            cp dash-icon.png AWSDash.AppDir/usr/share/icons/hicolor/256x256/apps/awsdash.png
            cp dash-icon.png AWSDash.AppDir/awsdash.png
          else
            touch AWSDash.AppDir/awsdash.png
          fi

          # Create .desktop file
          cat > AWSDash.AppDir/awsdash.desktop << 'DESKTOP'
          [Desktop Entry]
          Name=AWS Dash
          Exec=awsdash
          Icon=awsdash
          Type=Application
          Categories=Development;Utility;
          Comment=See all your AWS accounts, all your regions, in one window
          DESKTOP

          cp AWSDash.AppDir/awsdash.desktop AWSDash.AppDir/usr/share/applications/

          # Create AppRun script
          cat > AWSDash.AppDir/AppRun << 'APPRUN'
          #!/bin/bash
          SELF=$(readlink -f "$0")
          HERE=${SELF%/*}
          exec "${HERE}/usr/bin/awsdash" "$@"
          APPRUN
          chmod +x AWSDash.AppDir/AppRun

          # Build AppImage (--appimage-extract-and-run avoids FUSE requirement)
          ARCH=x86_64 ./appimagetool-x86_64.AppImage --appimage-extract-and-run AWSDash.AppDir AWSDash-x86_64.AppImage

      - name: Create Release and Upload Assets
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          # Determine tag name
          if [ "${{ github.event_name }}" == "push" ]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
          else
            TAG_NAME="${{ github.event.inputs.tag }}"
            if [ "$TAG_NAME" == "manual" ] || [ -z "$TAG_NAME" ]; then
              TAG_NAME="v$(date +%Y%m%d-%H%M%S)"
            fi
          fi

          echo "Creating release for tag: $TAG_NAME"

          # Create release
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${RELEASE_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"${TAG_NAME}\", \"name\": \"${TAG_NAME}\", \"body\": \"Linux release for ${TAG_NAME}\", \"draft\": false, \"prerelease\": false}" \
            "http://gitea:3000/api/v1/repos/${{ github.repository }}/releases")

          echo "Release response: $RELEASE_RESPONSE"

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')

          if [ "$RELEASE_ID" == "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "Failed to create release, trying to get existing..."
            RELEASE_ID=$(curl -s \
              -H "Authorization: token ${RELEASE_TOKEN}" \
              "http://gitea:3000/api/v1/repos/${{ github.repository }}/releases/tags/${TAG_NAME}" | jq -r '.id')
          fi

          echo "Release ID: $RELEASE_ID"

          if [ "$RELEASE_ID" != "null" ] && [ -n "$RELEASE_ID" ]; then
            # Upload tarball
            echo "Uploading tarball..."
            curl -X POST \
              -H "Authorization: token ${RELEASE_TOKEN}" \
              -F "attachment=@awsdash-linux-x86_64.tar.gz" \
              "http://gitea:3000/api/v1/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=awsdash-linux-x86_64.tar.gz"

            # Upload AppImage
            echo "Uploading AppImage..."
            curl -X POST \
              -H "Authorization: token ${RELEASE_TOKEN}" \
              -F "attachment=@AWSDash-x86_64.AppImage" \
              "http://gitea:3000/api/v1/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=AWSDash-x86_64.AppImage"

            echo "Release created successfully!"
          else
            echo "Failed to get release ID"
            exit 1
          fi
